### PR TITLE
[GNOME 40/DEPRECATION] Replaced deprecated property calls `margin_left/right` with `margin_start/end`

### PR DESCRIPTION
**Pull request by KoNickss**
**More info about the deprecation here:**

- https://valadoc.org/gtk+-3.0/Gtk.Widget.margin_left.html
- https://valadoc.org/gtk+-3.0/Gtk.Widget.margin_right.html

### CODE REVIEW

**Comment by KoNickss** [comment]
can you please check this out @ewlsh?

**Review by Florianb63 — APPROVED** [review]

**Comment by adrianoviana87** [comment]
I tried out this PR on Feadora 34 (wayland) and the error persists:
```
Gtk.BuilderError: /home/adriano/.local/share/gnome-shell/extensions/dash-to-dock@micxgx.gmail.com/Settings.ui:13:35 Invalid property: GtkBox.margin_left

Stack trace:
  DashToDock_Settings@/home/adriano/.local/share/gnome-shell/extensions/dash-to-dock@micxgx.gmail.com/prefs.js:92:23
  buildPrefsWidget@/home/adriano/.local/share/gnome-shell/extensions/dash-to-dock@micxgx.gmail.com/prefs.js:869:20
  _init@resource:///org/gnome/Shell/Extensions/js/extensionsService.js:209:40
  OpenExtensionPrefsAsync/<@resource:///org/gnome/Shell/Extensions/js/extensionsService.js:122:28
  asyncCallback@resource:///org/gnome/gjs/modules/core/overrides/Gio.js:115:22
  run@resource:///org/gnome/Shell/Extensions/js/dbusService.js:177:20
  main@resource:///org/gnome/Shell/Extensions/js/main.js:19:13
  run@resource:///org/gnome/gjs/modules/script/package.js:206:19
  start@resource:///org/gnome/gjs/modules/script/package.js:190:8
  @/usr/share/gnome-shell/org.gnome.Shell.Extensions:1:17
  
 ```

**Comment by adekmaulana** [comment]
> I tried out this PR on Feadora 34 (wayland) and the error persists:
> 
> ```
> Gtk.BuilderError: /home/adriano/.local/share/gnome-shell/extensions/dash-to-dock@micxgx.gmail.com/Settings.ui:13:35 Invalid property: GtkBox.margin_left
> 
> Stack trace:
>   DashToDock_Settings@/home/adriano/.local/share/gnome-shell/extensions/dash-to-dock@micxgx.gmail.com/prefs.js:92:23
>   buildPrefsWidget@/home/adriano/.local/share/gnome-shell/extensions/dash-to-dock@micxgx.gmail.com/prefs.js:869:20
>   _init@resource:///org/gnome/Shell/Extensions/js/extensionsService.js:209:40
>   OpenExtensionPrefsAsync/<@resource:///org/gnome/Shell/Extensions/js/extensionsService.js:122:28
>   asyncCallback@resource:///org/gnome/gjs/modules/core/overrides/Gio.js:115:22
>   run@resource:///org/gnome/Shell/Extensions/js/dbusService.js:177:20
>   main@resource:///org/gnome/Shell/Extensions/js/main.js:19:13
>   run@resource:///org/gnome/gjs/modules/script/package.js:206:19
>   start@resource:///org/gnome/gjs/modules/script/package.js:190:8
>   @/usr/share/gnome-shell/org.gnome.Shell.Extensions:1:17
>   
> ```

same, me too

**Comment by ewlsh** [comment]
These properties were already changed in `ewlsh/gnome-40`

https://github.com/ewlsh/dash-to-dock/commit/8ab13c0a1025abe42391589ae1b5ab7ff52dd5d5#diff-9f2258169752575e39e2f65645c244f7124ca2b0c24196bdc2ac75c55eab8730R11

Unless I'm missing something.

**Pull request closed without merging**
